FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Inkril.NotificationWorker/Inkril.NotificationWorker.csproj", "src/Inkril.NotificationWorker/"]
COPY ["src/Inkril.Application/Inkril.Application.csproj", "src/Inkril.Application/"]
COPY ["src/Inkril.Domain/Inkril.Domain.csproj", "src/Inkril.Domain/"]
RUN dotnet restore "src/Inkril.NotificationWorker/Inkril.NotificationWorker.csproj"

COPY . .
WORKDIR "/src/src/Inkril.NotificationWorker"
RUN dotnet build "Inkril.NotificationWorker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Inkril.NotificationWorker.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Inkril.NotificationWorker.dll"]
