FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Inkril.API/Inkril.API.csproj", "src/Inkril.API/"]
COPY ["src/Inkril.Application/Inkril.Application.csproj", "src/Inkril.Application/"]
COPY ["src/Inkril.Domain/Inkril.Domain.csproj", "src/Inkril.Domain/"]
COPY ["src/Inkril.Infrastructure/Inkril.Infrastructure.csproj", "src/Inkril.Infrastructure/"]
RUN dotnet restore "src/Inkril.API/Inkril.API.csproj"

COPY . .
WORKDIR "/src/src/Inkril.API"
RUN dotnet build "Inkril.API.csproj" -c Release -o /app/build

FROM build AS publish
WORKDIR "/src/src/Inkril.API"
RUN dotnet publish "Inkril.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Inkril.API.dll"]
